// Shared styles following Trello / Atlassian dark theme design tokens

export const styles = {
  wrapper: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans', sans-serif",
    padding: "16px",
    boxSizing: "border-box",
    background: "#1D2125",
    color: "#F7F8F9",
  },
  body: {
    fontSize: 13,
    color: "#9FADBC",
    marginBottom: 14,
    lineHeight: 1.5,
  },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 600,
    color: "#9FADBC",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  button: {
    width: "100%",
    padding: "9px 14px",
    borderRadius: 6,
    border: "none",
    background: "#579DFF",
    color: "#091E42",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "background 0.15s ease, transform 0.05s ease",
  },
  buttonBusy: {
    opacity: 0.75,
    cursor: "default",
  },
  buttonSecondary: {
    padding: "7px 12px",
    borderRadius: 4,
    border: "1px solid #454F59",
    background: "#22272B",
    color: "#F7F8F9",
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
  },
  subtleButton: {
    marginTop: 10,
    background: "none",
    border: "none",
    color: "#85B8FF",
    fontSize: 12,
    textDecoration: "underline",
    cursor: "pointer",
    padding: 0,
    width: "100%",
    textAlign: "center",
  },
  error: {
    fontSize: 12,
    color: "#F87168",
    marginTop: 8,
    lineHeight: 1.4,
  },
};

export const successStyles = {
  wrapper: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    background: "#1D2125",
    boxSizing: "border-box",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
  },
  centered: {
    alignItems: "center",
    textAlign: "center",
    padding: "20px 16px 16px",
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    background: "rgba(75, 206, 151, 0.15)",
    color: "#4BCE97",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  title: {
    fontSize: 15,
    fontWeight: 600,
    color: "#F7F8F9",
    margin: "0 0 6px",
  },
  body: {
    fontSize: 12.5,
    color: "#9FADBC",
    margin: "0 0 16px",
    lineHeight: 1.45,
  },
  button: {
    width: "100%",
    padding: "9px 14px",
    borderRadius: 6,
    border: "none",
    background: "#579DFF",
    color: "#091E42",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
};
